ALTER TABLE "recipes" ADD COLUMN IF NOT EXISTS "notes" TEXT;
ALTER TABLE "recipes" ADD COLUMN IF NOT EXISTS "prepTimeMin" INTEGER;
ALTER TABLE "recipes" ADD COLUMN IF NOT EXISTS "cookTimeMin" INTEGER;
